name: Make and emsdk CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v9
    - name: Verify
      run: emcc -v
      
    - uses: actions/checkout@v2
    - name: make
      run: make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libs
        path: |
          lib

    - name: Archive production artifacts2
      uses: actions/upload-artifact@v2
      with:
        name: mecab/src/.libs
        path: |
          mecab/src/.libs
